
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Month;
import java.time.Period;
import java.time.ZoneId;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;




/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class AddDonor extends javax.swing.JFrame {

    /**
     * Creates new form DonerDetails
     */
    String BloodGroup;
    String Gender; 
    private Date bday;
    public AddDonor() {
        initComponents();
        groupradioGender();
    }
    public void groupradioGender(){
        gendergroup.add(rbtnmale);
        gendergroup.add(rbtnfemale);
        }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gendergroup = new javax.swing.ButtonGroup();
        paneladd = new javax.swing.JPanel();
        lblnic = new javax.swing.JLabel();
        txtnic = new javax.swing.JTextField();
        lblfname = new javax.swing.JLabel();
        lbladrs = new javax.swing.JLabel();
        lblgender = new javax.swing.JLabel();
        lblBday = new javax.swing.JLabel();
        lblage = new javax.swing.JLabel();
        lbltele = new javax.swing.JLabel();
        lblblgroup = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        txtadrs = new javax.swing.JTextField();
        txtBday = new com.toedter.calendar.JDateChooser();
        txtage = new javax.swing.JTextField();
        txttele = new javax.swing.JTextField();
        cbBgroup = new javax.swing.JComboBox<>();
        btnadd = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        lblnewDoner = new javax.swing.JLabel();
        rbtnmale = new javax.swing.JRadioButton();
        rbtnfemale = new javax.swing.JRadioButton();
        lblbgimage = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        newdonormenu = new javax.swing.JMenu();
        updatemenu = new javax.swing.JMenu();
        alldonormenu = new javax.swing.JMenu();
        backmenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paneladd.setBackground(new java.awt.Color(0,0,0,20));

        lblnic.setBackground(new java.awt.Color(255, 255, 255));
        lblnic.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblnic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnic.setText("NIC");
        lblnic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));

        txtnic.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        txtnic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));
        txtnic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnicKeyPressed(evt);
            }
        });

        lblfname.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblfname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblfname.setText("FULL NAME");
        lblfname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));

        lbladrs.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lbladrs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbladrs.setText("ADDRESS");
        lbladrs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));

        lblgender.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblgender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblgender.setText("GENDER");
        lblgender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));

        lblBday.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblBday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBday.setText("BIRTH DATE");
        lblBday.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));

        lblage.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblage.setText("AGE");
        lblage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));

        lbltele.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lbltele.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltele.setText("TELEPHONE");
        lbltele.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));

        lblblgroup.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblblgroup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblblgroup.setText("BLOOD GROUP");
        lblblgroup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));

        txtfname.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        txtfname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));

        txtadrs.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        txtadrs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));
        txtadrs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtadrsKeyPressed(evt);
            }
        });

        txtBday.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));
        txtBday.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N

        txtage.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        txtage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));
        txtage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtageMouseClicked(evt);
            }
        });
        txtage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtageKeyPressed(evt);
            }
        });

        txttele.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        txttele.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));

        cbBgroup.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        cbBgroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<<Select Blood Group>>", "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        cbBgroup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));
        cbBgroup.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbBgroupItemStateChanged(evt);
            }
        });

        btnadd.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnadd.setText("ADD");
        btnadd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 255), 3, true));
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnclear.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnclear.setText("CLEAR");
        btnclear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 255), 3, true));
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        lblnewDoner.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        lblnewDoner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnewDoner.setText("Add New Doner");

        rbtnmale.setBackground(new java.awt.Color(255, 255, 255));
        rbtnmale.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbtnmale.setText("Male");
        rbtnmale.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 255), 2, true));
        rbtnmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnmaleActionPerformed(evt);
            }
        });

        rbtnfemale.setBackground(new java.awt.Color(255, 255, 255));
        rbtnfemale.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbtnfemale.setText("Female");
        rbtnfemale.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 255), 2, true));
        rbtnfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnfemaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneladdLayout = new javax.swing.GroupLayout(paneladd);
        paneladd.setLayout(paneladdLayout);
        paneladdLayout.setHorizontalGroup(
            paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneladdLayout.createSequentialGroup()
                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneladdLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblgender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblnic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblfname, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(lbladrs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneladdLayout.createSequentialGroup()
                                .addComponent(rbtnmale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbtnfemale, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtfname)
                            .addComponent(txtadrs))
                        .addGap(113, 113, 113)
                        .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblBday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbltele, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblblgroup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBday, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                            .addComponent(txtage)
                            .addComponent(txttele)
                            .addComponent(cbBgroup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(paneladdLayout.createSequentialGroup()
                        .addGap(453, 453, 453)
                        .addComponent(lblnewDoner, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneladdLayout.createSequentialGroup()
                        .addGap(444, 444, 444)
                        .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneladdLayout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(txtnic, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                        .addGap(543, 543, 543)))
                .addGap(97, 97, 97))
        );
        paneladdLayout.setVerticalGroup(
            paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneladdLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneladdLayout.createSequentialGroup()
                        .addComponent(lblnewDoner, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblnic)
                            .addComponent(txtnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBday, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtBday, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfname, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblage, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbladrs)
                    .addComponent(txtadrs, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltele, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblgender)
                    .addComponent(rbtnmale)
                    .addComponent(rbtnfemale)
                    .addComponent(lblblgroup, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbBgroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        getContentPane().add(paneladd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 1160, 450));

        lblbgimage.setBackground(new java.awt.Color(255, 255, 255));
        lblbgimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bg2.jpg"))); // NOI18N
        getContentPane().add(lblbgimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, 860));

        newdonormenu.setBackground(new java.awt.Color(255, 51, 51));
        newdonormenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Donor.png"))); // NOI18N
        newdonormenu.setText("Add New Doner            ");
        newdonormenu.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        newdonormenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newdonormenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newdonormenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(newdonormenu);

        updatemenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/blood-donor.png"))); // NOI18N
        updatemenu.setText("Update Doner Details     ");
        updatemenu.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        updatemenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatemenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(updatemenu);

        alldonormenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/more.png"))); // NOI18N
        alldonormenu.setText("All Doner Details          ");
        alldonormenu.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        alldonormenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alldonormenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(alldonormenu);

        backmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/exit.png"))); // NOI18N
        backmenu.setText("Back                                          ");
        backmenu.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        backmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backmenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(backmenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newdonormenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newdonormenuMouseClicked
       
    }//GEN-LAST:event_newdonormenuMouseClicked

    private void backmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backmenuMouseClicked
        Home frmNewForm = new Home();
        frmNewForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backmenuMouseClicked

    private void updatemenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatemenuMouseClicked
       UpdateDonor frmNewForm = new  UpdateDonor();
        frmNewForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_updatemenuMouseClicked

    private void alldonormenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alldonormenuMouseClicked
        AllDonor frmNewForm = new AllDonor();
        frmNewForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_alldonormenuMouseClicked

    private void txtnicKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnicKeyPressed
      /*   char nic = evt.getKeyChar();
        if(Character.isLetter(nic) || Character.isWhitespace(nic)){
        txtnic.setEditable(false);
        }
        else{
        txtnic.setEditable(true);
        }*/
      
    }//GEN-LAST:event_txtnicKeyPressed

    private void txtadrsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtadrsKeyPressed
       /* char Adrs = evt.getKeyChar();
        if(Character.isLetter( Adrs ) || Character.isWhitespace( Adrs )){
            txtadrs  .setEditable(true);
        }
        else{
            txtadrs  .setEditable(false);

        }*/
    }//GEN-LAST:event_txtadrsKeyPressed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed


              try{
                  Class.forName("com.mysql.cj.jdbc.Driver");
                  Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bloodbank","root","");

            String NIC = txtnic.getText();
            String FullName = txtfname.getText();
            String Address = txtadrs.getText();
            String Telephone= txttele.getText();
            //SimpleDateFormat sdf =new SimpleDateFormat("yyyy-MM-dd");
            Date day =txtBday.getDate();
            Date Birthdate= txtBday.getDate();
            String AGE = txtage.getText();
           
            if(NIC.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Please Enter NIC " );
            }
            
           else  if(!((NIC.matches("^([0-9]{9}[V])$") &&( NIC.length()==10))||NIC.matches("^([0-9]{12})$") &&( NIC.length()==12)))
            {
                JOptionPane.showMessageDialog(this,"Check Again NIC " );

            }

            else if(FullName.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Please Enter Your Name " );
            }

            else if(Address.isEmpty())
            {

                JOptionPane.showMessageDialog(this,"Please Enter Your Address " );
            }
             /* else  if(!((Address.matches("^(a-z A-Z 0-9 , /) $"))))
            {
                JOptionPane.showMessageDialog(this,"Check Again Address " );
            }*/
           else if(!rbtnmale.isSelected() && ! rbtnfemale.isSelected())
            {            
                JOptionPane.showMessageDialog(this,"Please Select Your Gender"  );
            }
            else if(txtBday.getDate()== null)
            {
                JOptionPane.showMessageDialog(this,"Please Enter Your Birthday"  );
  
            }
            else if(AGE.isEmpty())
            {
               JOptionPane.showMessageDialog(this,"Age is Neccessary"  );
   
            }
            else if(Telephone.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Enter your Telephone Number " );
            }
            else if(!(Telephone.matches("^([0-9]{10})$") &&( Telephone.length()==10)))
            {
                JOptionPane.showMessageDialog(this,"Check Again Telephone Number " );

            }
             else if(BloodGroup == null)
            {
                JOptionPane.showMessageDialog(this,"Please Select Your Blood Group"  );
  
            }
              else {
            // Check for duplicate NIC
            String checkQuery = "SELECT NIC FROM donordetails WHERE NIC = ?";
            PreparedStatement pstCheck = con.prepareStatement(checkQuery);
            pstCheck.setString(1, NIC);
            ResultSet rs = pstCheck.executeQuery();
            
            if(rs.next()) {
                JOptionPane.showMessageDialog(this, "You have already registered!");
            }
            
            else{
                Statement st = con.createStatement();
                String query1;
                query1 ="INSERT INTO donordetails(NIC,FullName,Address,Gender,Birthdate,Telephone,BloodGroup)"  + "VALUES('"+NIC+"','"+FullName+"','"+Address+"','"+Gender+"','"+Birthdate+"','"+Telephone+"','"+BloodGroup+"')";
                st.executeUpdate(query1);
                    txtnic.setText("");
                    txtfname.setText("");
                    txtadrs.setText("");
                    groupradioGender();
                    txtBday.setDate(null);
                    txtage.setText("");
                    txttele.setText(""); 
                    cbBgroup.setSelectedIndex(0);
                JOptionPane.showMessageDialog(this," Successfully Registered ! " );

                }
            }
           
            }
              
            catch(Exception ex)
            {
            JOptionPane.showMessageDialog(this,  ex );
            }
    }//GEN-LAST:event_btnaddActionPerformed

    private void cbBgroupItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbBgroupItemStateChanged
        BloodGroup = cbBgroup.getSelectedItem().toString();
    }//GEN-LAST:event_cbBgroupItemStateChanged

    private void rbtnmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnmaleActionPerformed
        Gender=rbtnmale.getText();
    }//GEN-LAST:event_rbtnmaleActionPerformed

    private void rbtnfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnfemaleActionPerformed
        Gender=rbtnfemale.getText();
    }//GEN-LAST:event_rbtnfemaleActionPerformed

    private void txtageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtageMouseClicked
            Date Birthdate= txtBday.getDate(); 
            LocalDate Bday = Birthdate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate now = LocalDate.now();
            Period age = Period.between(Bday, now);
            int Age = age.getYears();
            txtage.setText(Integer.toString(Age));
            if(Age<=18 || Age >=55)
            {
             JOptionPane.showMessageDialog(this,"Age Must Between 18 - 55 Years Old"  );
            
             txtage.setText("");
             txtBday.setDate(null);
            }
                         

    }//GEN-LAST:event_txtageMouseClicked

    private void txtageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtageKeyPressed
         char AGE = evt.getKeyChar();
        if(Character.isLetter( AGE ) || Character.isWhitespace( AGE ) || Character.isDigit(AGE )){
            txtage .setEditable(false);
        }
    }//GEN-LAST:event_txtageKeyPressed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        
       txtnic.setText("");
       txtfname.setText("");
       txtadrs.setText("");
       rbtnmale.setSelected(false);
       rbtnfemale.setSelected(false);
       txtBday.setDate(null);
       txtage.setText("");
       txttele.setText(""); 
       cbBgroup.setSelectedIndex(0);
      

    }//GEN-LAST:event_btnclearActionPerformed
    
    
  /*
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DonerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DonerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DonerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DonerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DonerDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu alldonormenu;
    private javax.swing.JMenu backmenu;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnclear;
    private javax.swing.JComboBox<String> cbBgroup;
    private javax.swing.ButtonGroup gendergroup;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblBday;
    private javax.swing.JLabel lbladrs;
    private javax.swing.JLabel lblage;
    private javax.swing.JLabel lblbgimage;
    private javax.swing.JLabel lblblgroup;
    private javax.swing.JLabel lblfname;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lblnewDoner;
    private javax.swing.JLabel lblnic;
    private javax.swing.JLabel lbltele;
    private javax.swing.JMenu newdonormenu;
    private javax.swing.JPanel paneladd;
    private javax.swing.JRadioButton rbtnfemale;
    private javax.swing.JRadioButton rbtnmale;
    private com.toedter.calendar.JDateChooser txtBday;
    private javax.swing.JTextField txtadrs;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtnic;
    private javax.swing.JTextField txttele;
    private javax.swing.JMenu updatemenu;
    // End of variables declaration//GEN-END:variables
}
