
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class AllExternalBloodSupplyDetails extends javax.swing.JFrame {

    /**
     * Creates new form DonerDetails
     */
    public AllExternalBloodSupplyDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneladd = new javax.swing.JPanel();
        lblnewDoner = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        bloodsupplymenu = new javax.swing.JMenu();
        internalsupply = new javax.swing.JMenu();
        externalsupply = new javax.swing.JMenu();
        allsupplymenu = new javax.swing.JMenu();
        Internalsupply = new javax.swing.JMenu();
        Externalsupply = new javax.swing.JMenu();
        backmenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paneladd.setBackground(new java.awt.Color(0,0,0,30));

        lblnewDoner.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        lblnewDoner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnewDoner.setText("All EX Supply Details");

        txtsearch.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/search.png"))); // NOI18N

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTable1.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ESupplyID", "ERequestID", "Blood Group", "SuppliedAmount", "Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout paneladdLayout = new javax.swing.GroupLayout(paneladd);
        paneladd.setLayout(paneladdLayout);
        paneladdLayout.setHorizontalGroup(
            paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneladdLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(307, 307, 307))
            .addGroup(paneladdLayout.createSequentialGroup()
                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneladdLayout.createSequentialGroup()
                        .addGap(435, 435, 435)
                        .addComponent(lblnewDoner, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneladdLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1029, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        paneladdLayout.setVerticalGroup(
            paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneladdLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblnewDoner, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneladdLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneladdLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        getContentPane().add(paneladd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 1160, 450));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bg2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1616, 719));

        bloodsupplymenu.setBackground(new java.awt.Color(255, 51, 51));
        bloodsupplymenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Donor.png"))); // NOI18N
        bloodsupplymenu.setText("Supply Details  ");
        bloodsupplymenu.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        bloodsupplymenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bloodsupplymenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bloodsupplymenuMouseClicked(evt);
            }
        });

        internalsupply.setBackground(new java.awt.Color(255, 51, 51));
        internalsupply.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Donor.png"))); // NOI18N
        internalsupply.setText("Internal Supply  ");
        internalsupply.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        internalsupply.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        internalsupply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                internalsupplyMouseClicked(evt);
            }
        });
        bloodsupplymenu.add(internalsupply);

        externalsupply.setBackground(new java.awt.Color(255, 51, 51));
        externalsupply.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Donor.png"))); // NOI18N
        externalsupply.setText("External Supply ");
        externalsupply.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        externalsupply.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        externalsupply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                externalsupplyMouseClicked(evt);
            }
        });
        bloodsupplymenu.add(externalsupply);

        jMenuBar1.add(bloodsupplymenu);

        allsupplymenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/more.png"))); // NOI18N
        allsupplymenu.setText("All Supply Details          ");
        allsupplymenu.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        allsupplymenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allsupplymenuMouseClicked(evt);
            }
        });

        Internalsupply.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/more.png"))); // NOI18N
        Internalsupply.setText("Internal Supply Details          ");
        Internalsupply.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        Internalsupply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InternalsupplyMouseClicked(evt);
            }
        });
        allsupplymenu.add(Internalsupply);

        Externalsupply.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/more.png"))); // NOI18N
        Externalsupply.setText("External Supply Details          ");
        Externalsupply.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        Externalsupply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExternalsupplyMouseClicked(evt);
            }
        });
        allsupplymenu.add(Externalsupply);

        jMenuBar1.add(allsupplymenu);

        backmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/exit.png"))); // NOI18N
        backmenu.setText("Back                                          ");
        backmenu.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        backmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backmenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(backmenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bloodsupplymenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bloodsupplymenuMouseClicked
      
    }//GEN-LAST:event_bloodsupplymenuMouseClicked

    private void backmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backmenuMouseClicked
        Home frmNewForm = new Home();
        frmNewForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backmenuMouseClicked

    private void allsupplymenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allsupplymenuMouseClicked
       
    }//GEN-LAST:event_allsupplymenuMouseClicked

    private void internalsupplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_internalsupplyMouseClicked
        InternalBloodSupply frmNewForm = new InternalBloodSupply ();
        frmNewForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_internalsupplyMouseClicked

    private void externalsupplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_externalsupplyMouseClicked
        ExternalBloodSupply frmNewForm = new ExternalBloodSupply ();
        frmNewForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_externalsupplyMouseClicked

    private void InternalsupplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InternalsupplyMouseClicked
         AllInternalBloodSupplyDetails frmNewForm = new  AllInternalBloodSupplyDetails  ();
        frmNewForm.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_InternalsupplyMouseClicked

    private void ExternalsupplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExternalsupplyMouseClicked
   
    }//GEN-LAST:event_ExternalsupplyMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
 try
        {
         Class.forName("com.mysql.cj.jdbc.Driver");
         Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bloodbank", "root", "");
         Statement st = con.createStatement();
         String query ="select * from externalsupply ";
        
         
            java.sql.ResultSet rs = st.executeQuery(query);
           
            while(rs.next()){
                
                String ESID = rs.getString("ESupplyID");
                String ERID = rs.getString("ERequestID");
                String amount = rs.getString("SuppliedAmount");
                String BloodGroup = rs.getString("BloodGroup");
                String Date = rs.getString("Date");
                String Status = rs.getString("Status");
              
                String tbDate[] = {ESID,ERID,BloodGroup,amount,Date,Status};
                DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                tblModel.addRow(tbDate);
            }
            
           
        }
        catch(Exception ex)
        {
             JOptionPane.showMessageDialog(this, "errorr in table       " + ex);

        }  
    }//GEN-LAST:event_formWindowActivated

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        
                
                DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                TableRowSorter<DefaultTableModel> Rowsorter = new TableRowSorter<>(tblModel);
                jTable1.setRowSorter(Rowsorter);
                Rowsorter.setRowFilter(RowFilter.regexFilter(txtsearch.getText()));
  
    }//GEN-LAST:event_txtsearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DonerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DonerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DonerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DonerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DonerDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Externalsupply;
    private javax.swing.JMenu Internalsupply;
    private javax.swing.JMenu allsupplymenu;
    private javax.swing.JMenu backmenu;
    private javax.swing.JMenu bloodsupplymenu;
    private javax.swing.JMenu externalsupply;
    private javax.swing.JMenu internalsupply;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblnewDoner;
    private javax.swing.JPanel paneladd;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
