/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class BloodSupplyDetails extends javax.swing.JFrame {

    /**
     * Creates new form DonerDetails
     */
    public BloodSupplyDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        bloodsupplymenu = new javax.swing.JMenu();
        internalsupply = new javax.swing.JMenu();
        externalsupply = new javax.swing.JMenu();
        allsupplymenu = new javax.swing.JMenu();
        Internalsupply = new javax.swing.JMenu();
        Externalsupply = new javax.swing.JMenu();
        backmenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bg.jpg"))); // NOI18N

        bloodsupplymenu.setBackground(new java.awt.Color(255, 51, 51));
        bloodsupplymenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Donor.png"))); // NOI18N
        bloodsupplymenu.setText("Supply Details  ");
        bloodsupplymenu.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        bloodsupplymenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bloodsupplymenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bloodsupplymenuMouseClicked(evt);
            }
        });

        internalsupply.setBackground(new java.awt.Color(255, 51, 51));
        internalsupply.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Donor.png"))); // NOI18N
        internalsupply.setText("Internal Supply  ");
        internalsupply.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        internalsupply.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        internalsupply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                internalsupplyMouseClicked(evt);
            }
        });
        bloodsupplymenu.add(internalsupply);

        externalsupply.setBackground(new java.awt.Color(255, 51, 51));
        externalsupply.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Donor.png"))); // NOI18N
        externalsupply.setText("External Supply ");
        externalsupply.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        externalsupply.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        externalsupply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                externalsupplyMouseClicked(evt);
            }
        });
        bloodsupplymenu.add(externalsupply);

        jMenuBar1.add(bloodsupplymenu);

        allsupplymenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/more.png"))); // NOI18N
        allsupplymenu.setText("All Supply Details          ");
        allsupplymenu.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        allsupplymenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allsupplymenuMouseClicked(evt);
            }
        });

        Internalsupply.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/more.png"))); // NOI18N
        Internalsupply.setText("Internal Supply Details          ");
        Internalsupply.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        Internalsupply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InternalsupplyMouseClicked(evt);
            }
        });
        allsupplymenu.add(Internalsupply);

        Externalsupply.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/more.png"))); // NOI18N
        Externalsupply.setText("External Supply Details          ");
        Externalsupply.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        Externalsupply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExternalsupplyMouseClicked(evt);
            }
        });
        allsupplymenu.add(Externalsupply);

        jMenuBar1.add(allsupplymenu);

        backmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/exit.png"))); // NOI18N
        backmenu.setText("Back                                          ");
        backmenu.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        backmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backmenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(backmenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1616, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bloodsupplymenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bloodsupplymenuMouseClicked
      
    }//GEN-LAST:event_bloodsupplymenuMouseClicked

    private void backmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backmenuMouseClicked
        Home frmNewForm = new Home();
        frmNewForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backmenuMouseClicked

    private void allsupplymenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allsupplymenuMouseClicked
       
    }//GEN-LAST:event_allsupplymenuMouseClicked

    private void internalsupplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_internalsupplyMouseClicked
        InternalBloodSupply frmNewForm = new InternalBloodSupply ();
       frmNewForm.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_internalsupplyMouseClicked

    private void externalsupplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_externalsupplyMouseClicked
        ExternalBloodSupply frmNewForm = new ExternalBloodSupply ();
        frmNewForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_externalsupplyMouseClicked

    private void InternalsupplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InternalsupplyMouseClicked
         AllInternalBloodSupplyDetails frmNewForm = new  AllInternalBloodSupplyDetails  ();
        frmNewForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InternalsupplyMouseClicked

    private void ExternalsupplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExternalsupplyMouseClicked
        AllExternalBloodSupplyDetails frmNewForm = new  AllExternalBloodSupplyDetails  ();
        frmNewForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ExternalsupplyMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DonerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DonerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DonerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DonerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DonerDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Externalsupply;
    private javax.swing.JMenu Internalsupply;
    private javax.swing.JMenu allsupplymenu;
    private javax.swing.JMenu backmenu;
    private javax.swing.JMenu bloodsupplymenu;
    private javax.swing.JMenu externalsupply;
    private javax.swing.JMenu internalsupply;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
