/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class BloodRequestDetails extends javax.swing.JFrame {

    /**
     * Creates new form DonerDetails
     */
    public BloodRequestDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        bloodrequestmenu = new javax.swing.JMenu();
        internalrequest = new javax.swing.JMenu();
        externalrequest = new javax.swing.JMenu();
        allrequestmenu = new javax.swing.JMenu();
        Internalrequest = new javax.swing.JMenu();
        Externalrequest = new javax.swing.JMenu();
        backmenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bg.jpg"))); // NOI18N

        bloodrequestmenu.setBackground(new java.awt.Color(255, 51, 51));
        bloodrequestmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Donor.png"))); // NOI18N
        bloodrequestmenu.setText("Add Request   ");
        bloodrequestmenu.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        bloodrequestmenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bloodrequestmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bloodrequestmenuMouseClicked(evt);
            }
        });

        internalrequest.setBackground(new java.awt.Color(255, 51, 51));
        internalrequest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Donor.png"))); // NOI18N
        internalrequest.setText("Internal Request   ");
        internalrequest.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        internalrequest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        internalrequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                internalrequestMouseClicked(evt);
            }
        });
        bloodrequestmenu.add(internalrequest);

        externalrequest.setBackground(new java.awt.Color(255, 51, 51));
        externalrequest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Donor.png"))); // NOI18N
        externalrequest.setText("External Request   ");
        externalrequest.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        externalrequest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        externalrequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                externalrequestMouseClicked(evt);
            }
        });
        bloodrequestmenu.add(externalrequest);

        jMenuBar1.add(bloodrequestmenu);

        allrequestmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/more.png"))); // NOI18N
        allrequestmenu.setText("All Request Details          ");
        allrequestmenu.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        allrequestmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allrequestmenuMouseClicked(evt);
            }
        });

        Internalrequest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/more.png"))); // NOI18N
        Internalrequest.setText("Internal Request Details          ");
        Internalrequest.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        Internalrequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InternalrequestMouseClicked(evt);
            }
        });
        allrequestmenu.add(Internalrequest);

        Externalrequest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/more.png"))); // NOI18N
        Externalrequest.setText("External Request Details          ");
        Externalrequest.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        Externalrequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExternalrequestMouseClicked(evt);
            }
        });
        allrequestmenu.add(Externalrequest);

        jMenuBar1.add(allrequestmenu);

        backmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/exit.png"))); // NOI18N
        backmenu.setText("Back                                          ");
        backmenu.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        backmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backmenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(backmenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1616, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bloodrequestmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bloodrequestmenuMouseClicked
      
    }//GEN-LAST:event_bloodrequestmenuMouseClicked

    private void backmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backmenuMouseClicked
        Home frmNewForm = new Home();
        frmNewForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backmenuMouseClicked

    private void allrequestmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allrequestmenuMouseClicked
       
    }//GEN-LAST:event_allrequestmenuMouseClicked

    private void internalrequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_internalrequestMouseClicked
        InternalBloodRequest frmNewForm = new InternalBloodRequest ();
        frmNewForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_internalrequestMouseClicked

    private void externalrequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_externalrequestMouseClicked
        ExternalBloodRequest frmNewForm = new ExternalBloodRequest ();
        frmNewForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_externalrequestMouseClicked

    private void InternalrequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InternalrequestMouseClicked
         AllInternalBloodRequestDetails frmNewForm = new  AllInternalBloodRequestDetails  ();
        frmNewForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InternalrequestMouseClicked

    private void ExternalrequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExternalrequestMouseClicked
        AllExternalBloodRequestDetails frmNewForm = new  AllExternalBloodRequestDetails  ();
        frmNewForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ExternalrequestMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DonerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DonerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DonerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DonerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DonerDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Externalrequest;
    private javax.swing.JMenu Internalrequest;
    private javax.swing.JMenu allrequestmenu;
    private javax.swing.JMenu backmenu;
    private javax.swing.JMenu bloodrequestmenu;
    private javax.swing.JMenu externalrequest;
    private javax.swing.JMenu internalrequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
