/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class DonerDetails extends javax.swing.JFrame {

    /**
     * Creates new form DonerDetails
     */
    public DonerDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        newdonormenu = new javax.swing.JMenu();
        updatemenu = new javax.swing.JMenu();
        alldonormenu = new javax.swing.JMenu();
        backmenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bg.jpg"))); // NOI18N

        newdonormenu.setBackground(new java.awt.Color(255, 51, 51));
        newdonormenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Donor.png"))); // NOI18N
        newdonormenu.setText("Add New Doner            ");
        newdonormenu.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        newdonormenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newdonormenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newdonormenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(newdonormenu);

        updatemenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/blood-donor.png"))); // NOI18N
        updatemenu.setText("Update Doner Details     ");
        updatemenu.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        updatemenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatemenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(updatemenu);

        alldonormenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/more.png"))); // NOI18N
        alldonormenu.setText("All Doner Details          ");
        alldonormenu.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        alldonormenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alldonormenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(alldonormenu);

        backmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/exit.png"))); // NOI18N
        backmenu.setText("Back                                          ");
        backmenu.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        backmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backmenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(backmenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1616, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newdonormenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newdonormenuMouseClicked
       AddDonor frmNewForm = new AddDonor();
        frmNewForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_newdonormenuMouseClicked

    private void backmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backmenuMouseClicked
        Home frmNewForm = new Home();
        frmNewForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backmenuMouseClicked

    private void updatemenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatemenuMouseClicked
        UpdateDonor frmNewForm = new  UpdateDonor();
        frmNewForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_updatemenuMouseClicked

    private void alldonormenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alldonormenuMouseClicked
       AllDonor frmNewForm = new AllDonor();
        frmNewForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_alldonormenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DonerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DonerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DonerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DonerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DonerDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu alldonormenu;
    private javax.swing.JMenu backmenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu newdonormenu;
    private javax.swing.JMenu updatemenu;
    // End of variables declaration//GEN-END:variables
}
