
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class Stock extends javax.swing.JFrame {

    /**
     * Creates new form DonerDetails
     */
    public Stock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneladd = new javax.swing.JPanel();
        lblnewDoner = new javax.swing.JLabel();
        AN = new javax.swing.JLabel();
        BP = new javax.swing.JLabel();
        BN = new javax.swing.JLabel();
        ON = new javax.swing.JLabel();
        AP = new javax.swing.JLabel();
        ABP = new javax.swing.JLabel();
        ABN = new javax.swing.JLabel();
        OP = new javax.swing.JLabel();
        txtAP = new javax.swing.JTextField();
        txtAN = new javax.swing.JTextField();
        txtAN1 = new javax.swing.JTextField();
        txtBN = new javax.swing.JTextField();
        txtOP = new javax.swing.JTextField();
        txtON = new javax.swing.JTextField();
        txtABP = new javax.swing.JTextField();
        txtABN = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        AllStockmenu = new javax.swing.JMenu();
        backmenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paneladd.setBackground(new java.awt.Color(0,0,0,20));

        lblnewDoner.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        lblnewDoner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnewDoner.setText("Stock Details");

        AN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/a-.jpg"))); // NOI18N

        BP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/b+.jpg"))); // NOI18N

        BN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/b-.jpg"))); // NOI18N

        ON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/o-.jpg"))); // NOI18N

        AP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/a+.jpg"))); // NOI18N

        ABP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ab+.jpg"))); // NOI18N

        ABN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ab-.jpg"))); // NOI18N

        OP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/o+.jpg"))); // NOI18N

        txtAP.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtAP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255), 3));
        txtAP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAPKeyTyped(evt);
            }
        });

        txtAN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtAN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255), 3));
        txtAN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtANKeyTyped(evt);
            }
        });

        txtAN1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtAN1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAN1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255), 3));
        txtAN1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAN1KeyTyped(evt);
            }
        });

        txtBN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtBN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255), 3));
        txtBN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBNKeyTyped(evt);
            }
        });

        txtOP.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtOP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255), 3));
        txtOP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOPKeyTyped(evt);
            }
        });

        txtON.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtON.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtON.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255), 3));
        txtON.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtONKeyTyped(evt);
            }
        });

        txtABP.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtABP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtABP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255), 3));
        txtABP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtABPKeyTyped(evt);
            }
        });

        txtABN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtABN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtABN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255), 3));
        txtABN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtABNKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout paneladdLayout = new javax.swing.GroupLayout(paneladd);
        paneladd.setLayout(paneladdLayout);
        paneladdLayout.setHorizontalGroup(
            paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneladdLayout.createSequentialGroup()
                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneladdLayout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addComponent(lblnewDoner, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneladdLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneladdLayout.createSequentialGroup()
                                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AP)
                                    .addComponent(AN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAN, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(121, 121, 121)
                                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBN)
                                    .addComponent(BN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAN1)))
                            .addComponent(txtAP, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100)
                        .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(OP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtON)
                            .addComponent(txtOP))
                        .addGap(104, 104, 104)
                        .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ABP)
                            .addComponent(ABN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtABN)
                            .addComponent(txtABP))))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        paneladdLayout.setVerticalGroup(
            paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneladdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblnewDoner, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AP, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ABP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneladdLayout.createSequentialGroup()
                        .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOP, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtAP, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAN1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtABP, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AN, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(BN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneladdLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ABN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ON, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtON, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtABN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        getContentPane().add(paneladd, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 1150, 530));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bg2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1616, 719));

        AllStockmenu.setBackground(new java.awt.Color(255, 51, 51));
        AllStockmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/blood-donor.png"))); // NOI18N
        AllStockmenu.setText("All Stock Details        ");
        AllStockmenu.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        AllStockmenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AllStockmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AllStockmenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(AllStockmenu);

        backmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/exit.png"))); // NOI18N
        backmenu.setText("Back                                          ");
        backmenu.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        backmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backmenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(backmenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AllStockmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AllStockmenuMouseClicked
      
         Stock frmNewForm = new Stock();
        frmNewForm.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_AllStockmenuMouseClicked

    private void backmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backmenuMouseClicked
        Home frmNewForm = new Home();
        frmNewForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backmenuMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      
         
        try
        {
         Class.forName("com.mysql.cj.jdbc.Driver");
         Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bloodbank", "root", "");
         Statement st = con.createStatement();
         
        
            String query ="select BloodGroup,Amount from Stock ";
            java.sql.ResultSet rs = st.executeQuery(query);
           
            while(rs.next()){
                
                
                String  BloodGroup = rs.getString("BloodGroup");
                int amount = rs.getInt("Amount");
                
                switch( BloodGroup){
                    case"A+":
                        txtAP.setText(Integer.toString(amount));
                        //lblAP.setText(Integer.toString(amount));
                        break;
                    case"A-":
                        txtAN.setText(Integer.toString(amount));
                        //lblAN.setText(Integer.toString(amount));
                        break;
                    case"B+":
                        txtAN1.setText(Integer.toString(amount));
                        //lblAP.setText(Integer.toString(amount));
                        break;
                    case"B-":
                        txtBN.setText(Integer.toString(amount));
                        //lblAN.setText(Integer.toString(amount));
                        break;
                    case"O+":
                        txtOP.setText(Integer.toString(amount));
                        //lblAP.setText(Integer.toString(amount));
                        break;
                    case"O-":
                        txtON.setText(Integer.toString(amount));
                        //lblAN.setText(Integer.toString(amount));
                        break;
                    case"AB+":
                        txtABP.setText(Integer.toString(amount));
                        //lblAP.setText(Integer.toString(amount));
                        break;    
                    case"AB-":
                        txtABN.setText(Integer.toString(amount));
                        //lblAN.setText(Integer.toString(amount));
                        break;
                }
                
               
            }
                
        
        }
        catch(Exception ex)
        {
             JOptionPane.showMessageDialog(this, "errorr in Stock    " + ex);

        }  
    }//GEN-LAST:event_formWindowActivated

    private void txtAPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAPKeyTyped
         evt.consume();
                     
    }//GEN-LAST:event_txtAPKeyTyped

    private void txtAN1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAN1KeyTyped
        evt.consume();
    }//GEN-LAST:event_txtAN1KeyTyped

    private void txtOPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOPKeyTyped
         evt.consume();
    }//GEN-LAST:event_txtOPKeyTyped

    private void txtABPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtABPKeyTyped
         evt.consume();
    }//GEN-LAST:event_txtABPKeyTyped

    private void txtANKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtANKeyTyped
         evt.consume();
    }//GEN-LAST:event_txtANKeyTyped

    private void txtBNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBNKeyTyped
        evt.consume();
    }//GEN-LAST:event_txtBNKeyTyped

    private void txtONKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtONKeyTyped
       evt.consume();
    }//GEN-LAST:event_txtONKeyTyped

    private void txtABNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtABNKeyTyped
        evt.consume();
    }//GEN-LAST:event_txtABNKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DonerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DonerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DonerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DonerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DonerDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ABN;
    private javax.swing.JLabel ABP;
    private javax.swing.JLabel AN;
    private javax.swing.JLabel AP;
    private javax.swing.JMenu AllStockmenu;
    private javax.swing.JLabel BN;
    private javax.swing.JLabel BP;
    private javax.swing.JLabel ON;
    private javax.swing.JLabel OP;
    private javax.swing.JMenu backmenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblnewDoner;
    private javax.swing.JPanel paneladd;
    private javax.swing.JTextField txtABN;
    private javax.swing.JTextField txtABP;
    private javax.swing.JTextField txtAN;
    private javax.swing.JTextField txtAN1;
    private javax.swing.JTextField txtAP;
    private javax.swing.JTextField txtBN;
    private javax.swing.JTextField txtON;
    private javax.swing.JTextField txtOP;
    // End of variables declaration//GEN-END:variables
}
