
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author User
 */
public class UpdateDonor extends javax.swing.JFrame {

    /**
     * Creates new form DonerDetails
     */
    String BloodGroup;
    String Gender;
    private Date bday;

    public UpdateDonor() {
        initComponents();
        //groupradioGender();
    }

    /* public void groupradioGender() {
        gendergroup.add(rbtnmale);
        gendergroup.add(rbtnfemale);

    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gendergroup = new javax.swing.ButtonGroup();
        paneladd = new javax.swing.JPanel();
        lblnic = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        lblfname = new javax.swing.JLabel();
        lbladrs = new javax.swing.JLabel();
        lblgender = new javax.swing.JLabel();
        lblBday = new javax.swing.JLabel();
        lbltele = new javax.swing.JLabel();
        lblblgroup = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        txtadrs = new javax.swing.JTextField();
        txttele = new javax.swing.JTextField();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        lblUpdate = new javax.swing.JLabel();
        txtgender = new javax.swing.JTextField();
        txtbday = new javax.swing.JTextField();
        txtbgroup = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        txtnic = new javax.swing.JTextField();
        lblsearch = new javax.swing.JLabel();
        lblbgimage = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        newdonormenu = new javax.swing.JMenu();
        updatemenu = new javax.swing.JMenu();
        alldonormenu = new javax.swing.JMenu();
        backmenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paneladd.setBackground(new java.awt.Color(0,0,0,20));

        lblnic.setBackground(new java.awt.Color(255, 255, 255));
        lblnic.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblnic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnic.setText("NIC");
        lblnic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));

        txtsearch.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        txtsearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));

        lblfname.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblfname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblfname.setText("FULL NAME");
        lblfname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));

        lbladrs.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lbladrs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbladrs.setText("ADDRESS");
        lbladrs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));

        lblgender.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblgender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblgender.setText("GENDER");
        lblgender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));

        lblBday.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblBday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBday.setText("BIRTH DATE");
        lblBday.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));

        lbltele.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lbltele.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltele.setText("TELEPHONE");
        lbltele.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));

        lblblgroup.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblblgroup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblblgroup.setText("BLOOD GROUP");
        lblblgroup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));

        txtfname.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        txtfname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));

        txtadrs.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        txtadrs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));

        txttele.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        txttele.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));

        btnupdate.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnupdate.setText("Update");
        btnupdate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 255), 3, true));
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btndelete.setText("Delete");
        btndelete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 255), 3, true));
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        lblUpdate.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        lblUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUpdate.setText("Update Doner Details");

        txtgender.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        txtgender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));

        txtbday.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        txtbday.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));

        txtbgroup.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        txtbgroup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));

        btnsearch.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnsearch.setText("Search");
        btnsearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 255), 3, true));
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        txtnic.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        txtnic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));

        lblsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsearchMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout paneladdLayout = new javax.swing.GroupLayout(paneladd);
        paneladd.setLayout(paneladdLayout);
        paneladdLayout.setHorizontalGroup(
            paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneladdLayout.createSequentialGroup()
                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneladdLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblgender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblnic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblfname, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(lbladrs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtfname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtadrs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(txtgender)
                            .addComponent(txtnic, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(113, 113, 113)
                        .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblBday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbltele, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblblgroup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txttele, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                            .addComponent(txtbday)
                            .addComponent(txtbgroup)))
                    .addGroup(paneladdLayout.createSequentialGroup()
                        .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneladdLayout.createSequentialGroup()
                                .addGap(291, 291, 291)
                                .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneladdLayout.createSequentialGroup()
                                .addGap(350, 350, 350)
                                .addComponent(lblUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 357, Short.MAX_VALUE)))
                .addGap(96, 96, 96))
            .addGroup(paneladdLayout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblsearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneladdLayout.setVerticalGroup(
            paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneladdLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneladdLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneladdLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnic)
                    .addComponent(lblBday, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbday, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfname, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltele, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbladrs)
                    .addComponent(txtadrs, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblblgroup, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbgroup, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblgender)
                    .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(paneladd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 1160, 450));

        lblbgimage.setBackground(new java.awt.Color(255, 255, 255));
        lblbgimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bg2.jpg"))); // NOI18N
        getContentPane().add(lblbgimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, 860));

        newdonormenu.setBackground(new java.awt.Color(255, 51, 51));
        newdonormenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Donor.png"))); // NOI18N
        newdonormenu.setText("Add New Doner            ");
        newdonormenu.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        newdonormenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newdonormenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newdonormenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(newdonormenu);

        updatemenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/blood-donor.png"))); // NOI18N
        updatemenu.setText("Update Doner Details     ");
        updatemenu.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jMenuBar1.add(updatemenu);

        alldonormenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/more.png"))); // NOI18N
        alldonormenu.setText("All Doner Details          ");
        alldonormenu.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        alldonormenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alldonormenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(alldonormenu);

        backmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/exit.png"))); // NOI18N
        backmenu.setText("Back                                          ");
        backmenu.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        backmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backmenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(backmenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newdonormenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newdonormenuMouseClicked
        AddDonor frmNewForm = new AddDonor();
        frmNewForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_newdonormenuMouseClicked

    private void backmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backmenuMouseClicked
        Home frmNewForm = new Home();
        frmNewForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backmenuMouseClicked

    private void alldonormenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alldonormenuMouseClicked
        AllDonor frmNewForm = new AllDonor();
        frmNewForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_alldonormenuMouseClicked

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
      
        String NIC = txtsearch.getText();
        try{
             Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bloodbank","root","");
             Statement st = con.createStatement();
             ResultSet rs =st.executeQuery("select * from donordetails where NIC= '"+NIC+"'");
             if(rs.next( ))
             {
                txtnic.setText(rs.getString(2));
                txtfname.setText(rs.getString(3));
                txtadrs.setText(rs.getString(4));
                txtgender.setText(rs.getString(5));
                txtbday.setText(rs.getString(6));
                txttele.setText(rs.getString(7));
                txtbgroup.setText(rs.getString(8));
                 btnupdate.setEnabled(true);
                btndelete.setEnabled(true);
             }
             else
             {
                 
                 JOptionPane.showMessageDialog(this,"Donor Doesn't Exits" );

             }
        }
        catch(Exception ex)
        {
                 JOptionPane.showMessageDialog(this,"Error in Search" + ex);
        }
              
    }//GEN-LAST:event_btnsearchActionPerformed

    private void lblsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsearchMouseClicked
        String NIC = txtsearch.getText();
        try{
             Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bloodbank","root","");
             Statement st = con.createStatement();
             ResultSet rs =st.executeQuery("select * from donordetails where NIC= '"+NIC+"'");
             if(rs.next( ))
             {
                txtnic.setText(rs.getString(2));
                txtfname.setText(rs.getString(3));
                txtadrs.setText(rs.getString(4));
                txtgender.setText(rs.getString(5));
                txtbday.setText(rs.getString(6));
                txttele.setText(rs.getString(7));
                txtbgroup.setText(rs.getString(8));
               btnupdate.setEnabled(true);
               btndelete.setEnabled(true);
             }
             else
             {
                 
                 JOptionPane.showMessageDialog(this,"Donor Doesn't Exits" );

             }
        }
        catch(Exception ex)
        {
                 JOptionPane.showMessageDialog(this,"Error in Search" + ex);
        }    }//GEN-LAST:event_lblsearchMouseClicked

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
            String NIC = txtnic.getText();
            String FullName = txtfname.getText();
            String Address = txtadrs.getText();
            String Gender = txtgender.getText();
            String Birthdate= txtbday.getText();
            String Telephone= txttele.getText();
            String BloodGroup= txtbgroup.getText();
            try
            {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bloodbank","root","");
                Statement st = con.createStatement();
               
                
                st.executeUpdate("update donordetails set FullName ='"+FullName+"' where NIC = '"+NIC+"'");
                st.executeUpdate("update donordetails set Address ='"+Address+"' where NIC = '"+NIC+"'");
                st.executeUpdate("update donordetails set Telephone ='"+Telephone+"' where NIC = '"+NIC+"'");
                JOptionPane.showMessageDialog(this,"Successfully Updated" );
                    txtnic.setText("");
                    txtfname.setText("");
                    txtadrs.setText("");
                    txtgender.setText("");
                    txtbday.setText("");
                    txttele.setText(""); 
                    txtbgroup.setText("");
              
            }
            catch(Exception ex)
            {
                 JOptionPane.showMessageDialog(this,"Error in Update" + ex);
            }
            
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
            String NIC = txtnic.getText();
            /*String FullName = txtfname.getText();
            String Address = txtadrs.getText();
            String Gender = txtgender.getText();
            String Birthdate= txtbday.getText();
            String Telephone= txttele.getText();
            String BloodGroup= txtbgroup.getText();*/
            try
            {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bloodbank","root","");
                Statement st = con.createStatement();
                st.executeUpdate("delete from donordetails where NIC = '"+NIC+"'");
                
               JOptionPane.showMessageDialog(this,"Successfully Deleted" );
                    txtnic.setText("");
                    txtfname.setText("");
                    txtadrs.setText("");
                    txtgender.setText("");
                    txtbday.setText("");
                    txttele.setText(""); 
                    txtbgroup.setText("");
            }
            catch(Exception ex)
            {
                 JOptionPane.showMessageDialog(this,"Error in Deletion" + ex);
            }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
          btnupdate.setEnabled(false);
                btndelete.setEnabled(false);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DonerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DonerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DonerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DonerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DonerDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu alldonormenu;
    private javax.swing.JMenu backmenu;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate;
    private javax.swing.ButtonGroup gendergroup;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblBday;
    private javax.swing.JLabel lblUpdate;
    private javax.swing.JLabel lbladrs;
    private javax.swing.JLabel lblbgimage;
    private javax.swing.JLabel lblblgroup;
    private javax.swing.JLabel lblfname;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lblnic;
    private javax.swing.JLabel lblsearch;
    private javax.swing.JLabel lbltele;
    private javax.swing.JMenu newdonormenu;
    private javax.swing.JPanel paneladd;
    private javax.swing.JTextField txtadrs;
    private javax.swing.JTextField txtbday;
    private javax.swing.JTextField txtbgroup;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtnic;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txttele;
    private javax.swing.JMenu updatemenu;
    // End of variables declaration//GEN-END:variables
}
